# These are supported funding model platforms

github: [shiba4life]
patreon: https://patreon.com/EuclidCodes?utm_medium=unknown&utm_source=join_link&utm_campaign=creatorshare_creator&utm_content=copyLink
