# DataFold Logging Configuration Examples
# This file contains various configuration examples for different environments and use cases

# =============================================================================
# DEVELOPMENT ENVIRONMENT CONFIGURATION
# =============================================================================
# High verbosity, console-focused, with detailed debugging information

[development.general]
default_level = "DEBUG"
enable_colors = true
enable_correlation_ids = true
max_correlation_id_length = 64

[development.outputs.console]
enabled = true
level = "DEBUG"
colors = true
include_timestamp = true
include_module = true
include_thread = false

[development.outputs.file]
enabled = true
path = "logs/dev/datafold-dev.log"
level = "TRACE"
max_size = "50MB"
max_files = 3
include_timestamp = true
include_module = true
include_thread = true

[development.outputs.web]
enabled = true
level = "DEBUG"
buffer_size = 2000
enable_filtering = true
max_logs = 10000

[development.outputs.structured]
enabled = false
level = "DEBUG"
include_context = true
include_metrics = false

# Feature levels optimized for development
[development.features]
transform = "TRACE"        # Maximum detail for transform debugging
network = "DEBUG"          # Network debugging for P2P development
database = "DEBUG"         # Database operation debugging
schema = "DEBUG"           # Schema validation debugging
query = "DEBUG"            # Query optimization debugging
mutation = "INFO"          # Mutation operations
permissions = "INFO"       # Permission system
http_server = "DEBUG"      # HTTP API debugging
tcp_server = "DEBUG"       # TCP protocol debugging
ingestion = "DEBUG"        # Data ingestion debugging

# =============================================================================
# STAGING ENVIRONMENT CONFIGURATION
# =============================================================================
# Balanced logging for pre-production testing

[staging.general]
default_level = "INFO"
enable_colors = false      # No colors in staging logs
enable_correlation_ids = true
max_correlation_id_length = 32

[staging.outputs.console]
enabled = true
level = "INFO"
colors = false
include_timestamp = true
include_module = true
include_thread = false

[staging.outputs.file]
enabled = true
path = "/var/log/datafold/staging.log"
level = "DEBUG"
max_size = "100MB"
max_files = 5
include_timestamp = true
include_module = true
include_thread = true

[staging.outputs.web]
enabled = true
level = "INFO"
buffer_size = 1000
enable_filtering = true
max_logs = 5000

[staging.outputs.structured]
enabled = true
level = "INFO"
path = "/var/log/datafold/staging-structured.json"
include_context = true
include_metrics = true

[staging.features]
transform = "INFO"
network = "INFO"
database = "WARN"         # Reduce database noise in staging
schema = "INFO"
query = "INFO"
mutation = "INFO"
permissions = "INFO"
http_server = "DEBUG"     # Still debug HTTP for API testing
tcp_server = "INFO"
ingestion = "INFO"

# =============================================================================
# PRODUCTION ENVIRONMENT CONFIGURATION
# =============================================================================
# Minimal logging optimized for performance and operational monitoring

[production.general]
default_level = "WARN"
enable_colors = false
enable_correlation_ids = true
max_correlation_id_length = 16

[production.outputs.console]
enabled = false            # No console output in production

[production.outputs.file]
enabled = true
path = "/var/log/datafold/production.log"
level = "INFO"
max_size = "500MB"
max_files = 10
include_timestamp = true
include_module = true
include_thread = false

[production.outputs.web]
enabled = false            # Disable web streaming in production

[production.outputs.structured]
enabled = true
level = "INFO"
path = "/var/log/datafold/production-structured.json"
include_context = false    # Minimal context for performance
include_metrics = true

[production.features]
transform = "WARN"         # Only warnings and errors
network = "WARN"
database = "ERROR"         # Only critical database issues
schema = "WARN"
query = "WARN"
mutation = "WARN"
permissions = "WARN"       # Security events
http_server = "INFO"       # Track API usage
tcp_server = "WARN"
ingestion = "WARN"

# =============================================================================
# DEBUGGING SPECIFIC FEATURES
# =============================================================================
# Examples for debugging specific components

# Transform System Debugging
[debug_transforms.general]
default_level = "INFO"
enable_colors = true
enable_correlation_ids = true

[debug_transforms.outputs.console]
enabled = true
level = "TRACE"
colors = true
include_timestamp = true
include_module = true
include_thread = false

[debug_transforms.outputs.file]
enabled = true
path = "logs/debug/transforms.log"
level = "TRACE"
max_size = "10MB"
max_files = 2

[debug_transforms.features]
transform = "TRACE"        # Maximum detail for transforms
network = "ERROR"         # Minimal network logging
database = "ERROR"        # Minimal database logging
schema = "WARN"           # Schema issues only
query = "ERROR"
mutation = "ERROR"
permissions = "ERROR"
http_server = "ERROR"
tcp_server = "ERROR"
ingestion = "ERROR"

# Network System Debugging
[debug_network.general]
default_level = "INFO"
enable_colors = true
enable_correlation_ids = true

[debug_network.outputs.console]
enabled = true
level = "TRACE"
colors = true

[debug_network.outputs.file]
enabled = true
path = "logs/debug/network.log"
level = "TRACE"

[debug_network.features]
transform = "ERROR"
network = "TRACE"         # Maximum detail for network
database = "ERROR"
schema = "ERROR"
query = "ERROR"
mutation = "ERROR"
permissions = "ERROR"
http_server = "INFO"      # HTTP might be relevant for network debugging
tcp_server = "DEBUG"      # TCP server for P2P
ingestion = "ERROR"

# Schema System Debugging
[debug_schema.general]
default_level = "INFO"
enable_colors = true
enable_correlation_ids = true

[debug_schema.outputs.console]
enabled = true
level = "TRACE"
colors = true

[debug_schema.outputs.file]
enabled = true
path = "logs/debug/schema.log"
level = "TRACE"

[debug_schema.features]
transform = "WARN"        # Transforms might affect schemas
network = "ERROR"
database = "WARN"        # Database operations for schema storage
schema = "TRACE"          # Maximum detail for schema system
query = "ERROR"
mutation = "ERROR"
permissions = "WARN"      # Permission validation
http_server = "INFO"      # Schema API endpoints
tcp_server = "ERROR"
ingestion = "WARN"        # Ingestion affects schemas

# =============================================================================
# PERFORMANCE MONITORING CONFIGURATION
# =============================================================================
# Optimized for performance analysis and monitoring

[performance.general]
default_level = "INFO"
enable_colors = false
enable_correlation_ids = true
max_correlation_id_length = 32

[performance.outputs.console]
enabled = true
level = "INFO"
colors = false
include_timestamp = true
include_module = false     # Reduce noise for performance focus
include_thread = false

[performance.outputs.file]
enabled = true
path = "logs/performance/performance.log"
level = "INFO"
max_size = "200MB"
max_files = 7

[performance.outputs.structured]
enabled = true
level = "INFO"
path = "logs/performance/performance-metrics.json"
include_context = true
include_metrics = true     # Essential for performance monitoring

[performance.features]
transform = "INFO"         # Transform performance is critical
network = "INFO"           # Network latency matters
database = "INFO"          # Database performance monitoring
schema = "WARN"            # Schema ops are usually fast
query = "INFO"             # Query performance monitoring
mutation = "INFO"          # Mutation performance
permissions = "WARN"       # Permission checks should be fast
http_server = "INFO"       # API response times
tcp_server = "INFO"        # TCP performance
ingestion = "INFO"         # Ingestion throughput

# =============================================================================
# TESTING ENVIRONMENT CONFIGURATION
# =============================================================================
# Configuration for unit and integration tests

[testing.general]
default_level = "DEBUG"
enable_colors = true
enable_correlation_ids = false  # Simpler for tests

[testing.outputs.console]
enabled = true
level = "DEBUG"
colors = true
include_timestamp = false   # Cleaner test output
include_module = true
include_thread = false

[testing.outputs.file]
enabled = true
path = "target/test-logs/test.log"
level = "TRACE"
max_size = "50MB"
max_files = 1

[testing.outputs.web]
enabled = false            # Not needed for tests

[testing.outputs.structured]
enabled = false            # Keep tests simple

[testing.features]
transform = "DEBUG"
network = "DEBUG"
database = "DEBUG"
schema = "DEBUG"
query = "DEBUG"
mutation = "DEBUG"
permissions = "DEBUG"
http_server = "DEBUG"
tcp_server = "DEBUG"
ingestion = "DEBUG"

# =============================================================================
# CONTAINER/DOCKER CONFIGURATION
# =============================================================================
# Optimized for containerized deployments

[container.general]
default_level = "INFO"
enable_colors = false      # No colors for container logs
enable_correlation_ids = true

[container.outputs.console]
enabled = true             # Primary output for containers
level = "INFO"
colors = false
include_timestamp = true
include_module = true
include_thread = false

[container.outputs.file]
enabled = false            # Use container logging instead

[container.outputs.web]
enabled = false            # Not suitable for containers

[container.outputs.structured]
enabled = true             # Structured logs to stdout
level = "INFO"
path = null                # Output to stdout for container logging
include_context = true
include_metrics = true

[container.features]
transform = "INFO"
network = "INFO"
database = "WARN"
schema = "INFO"
query = "INFO"
mutation = "INFO"
permissions = "WARN"
http_server = "INFO"
tcp_server = "INFO"
ingestion = "INFO"

# =============================================================================
# HIGH-THROUGHPUT CONFIGURATION
# =============================================================================
# Minimal logging for high-performance scenarios

[high_throughput.general]
default_level = "WARN"
enable_colors = false
enable_correlation_ids = false  # Reduce overhead

[high_throughput.outputs.console]
enabled = false            # No console output

[high_throughput.outputs.file]
enabled = true
path = "/var/log/datafold/high-throughput.log"
level = "ERROR"            # Only errors
max_size = "1GB"
max_files = 3
include_timestamp = true
include_module = false     # Minimal formatting
include_thread = false

[high_throughput.outputs.web]
enabled = false

[high_throughput.outputs.structured]
enabled = false            # No structured logging for max performance

[high_throughput.features]
transform = "ERROR"        # Only critical issues
network = "ERROR"
database = "ERROR"
schema = "ERROR"
query = "ERROR"
mutation = "ERROR"
permissions = "ERROR"
http_server = "WARN"       # Some HTTP monitoring
tcp_server = "ERROR"
ingestion = "ERROR"

# =============================================================================
# SECURITY AUDIT CONFIGURATION
# =============================================================================
# Enhanced logging for security monitoring

[security_audit.general]
default_level = "INFO"
enable_colors = false
enable_correlation_ids = true
max_correlation_id_length = 64  # Longer IDs for audit trails

[security_audit.outputs.console]
enabled = false

[security_audit.outputs.file]
enabled = true
path = "/var/log/datafold/security-audit.log"
level = "INFO"
max_size = "100MB"
max_files = 30             # Keep longer history
include_timestamp = true
include_module = true
include_thread = true      # Thread info for security analysis

[security_audit.outputs.structured]
enabled = true
level = "INFO"
path = "/var/log/datafold/security-audit.json"
include_context = true     # Full context for security events
include_metrics = false

[security_audit.features]
transform = "WARN"
network = "INFO"           # Network connections are security-relevant
database = "WARN"
schema = "INFO"            # Schema changes are security events
query = "INFO"             # Query patterns for security analysis
mutation = "INFO"          # Data modifications
permissions = "DEBUG"      # Detailed permission logging
http_server = "INFO"       # All HTTP requests
tcp_server = "INFO"        # TCP connections
ingestion = "INFO"         # Data ingestion events

# =============================================================================
# MINIMAL CONFIGURATION
# =============================================================================
# Absolute minimum logging for resource-constrained environments

[minimal.general]
default_level = "ERROR"
enable_colors = false
enable_correlation_ids = false

[minimal.outputs.console]
enabled = true
level = "ERROR"
colors = false
include_timestamp = false
include_module = false
include_thread = false

[minimal.outputs.file]
enabled = false

[minimal.outputs.web]
enabled = false

[minimal.outputs.structured]
enabled = false

[minimal.features]
transform = "ERROR"
network = "ERROR"
database = "ERROR"
schema = "ERROR"
query = "ERROR"
mutation = "ERROR"
permissions = "ERROR"
http_server = "ERROR"
tcp_server = "ERROR"
ingestion = "ERROR"